DECLARE
Vno_cia arinda2.no_cia%type;
Vclase arinda2.clase%type;
Vcategoria arinda2.categoria%TYPE;
Vno_arti arinda2.no_arti%TYPE;
Vdescripcion arinda2.descripcion%TYPE;
Vunidad arinda2.unidad%TYPE;
Vpeso arinda2.peso%TYPE;
Vtiempo_rep arinda2.tiempo_rep%TYPE;
Vcodigo arinda2.codigo%TYPE;
Vtransito arinda2.transito%TYPE;
Vupc arinda2.upc%TYPE;
Vmarca arinda2.marca%TYPE;
Vgrupo arinda2.grupo%TYPE;
Vmaximo arinda2.maximo%TYPE;
Vminimo 
Vreorden ,
Vmoneda_preciobase ,
Vpreciobase ,
Vprecionuevo ,
Vmoneda_precionuevo ,
Vimp_ven ,
Vfabricacion ,
Vpromoapp ,
Vdisc_exc ,
Vconttype ,
Vind_lote ,
Vind_activo ,
Vgracia_vencer ,
Vcosto_nuevo ,
Vcosto_estandar ,
Vaplica_impuesto ,
Vnombre_largo ,
Vind_imprime_garantia ,
Vind_requiere_serie ,
Vind_es_para_oferta ,
Vgarantia ,
Vind_importa ,
Vcubicaje ,
Vbase_tarima ,
Valto_tarima ,
Vtipo_almacen ,
Vcodigo_arancel ,
Vdescripcion_ingles ,
Vtraduccion_descri ,
Vtipo_producto ,
Vind_permiso_salud ,
Vtipo_liquida ,
Vdias_util ,
Vdescripcion_alterna ,
Vtstamp ,
Vcod_ante ,
Vcpe ,
Vmpps ,
Vdescripcion_comercial ,
Vcod_sub_rubro ,
Vsub_rubro ,
Vcantidad_medida ,
Vcod_unidad_sundecop ,
Vunidad_sundecop ,
Vcod_marca_sundecop ,
Vmarca_sundecop ,
Vcod_forma ,
Vforma ,
Vcod_material ,
Vmaterial ,
Vcod_rubro ,
Vrubro 